name: Deploy MkDocs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          pip install mkdocs mkdocs-material mkdocs-i18n

      - name: Verificar estructura
        run: |
          ls -la
          if [ -f "mkdocs.yml" ]; then
            echo "mkdocs.yml encontrado"
          else
            echo "ERROR: mkdocs.yml no encontrado"
            exit 1
          fi

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generar y desplegar
        run: mkdocs gh-deploy --force